### PR TITLE
Additional app extensions for Windows

### PR DESCRIPTION
**Pull request by neojp**
`.appref-ms` is the Universal Windows Platform app extension
`.exe` is the common Windows executable extension

### CODE REVIEW

**Comment by linonetwo** [comment]
Thanks for your contribution, can you try to add some test for these two extensions?

**Comment by linonetwo** [comment]
Just add tests for the windows part, don't mind the MacOS part which fails for some other reason.

**Comment by neojp** [comment]
@linonetwo Tests have been added.

**Comment by neojp** [comment]
This PR should also close issue #37

**Comment by linonetwo** [comment]
Cool, glad to see that.

**Pull request merged**
