### PR TITLE
Add support for abbreviation app name

### PR DESCRIPTION
**Pull request by nantaphop**
Add ability to search app with abbreviation name. Such as query "as" will be match "Android Studio".

Also support some app that title difference from its *.app like Virtual Studio Code that come with title "Code" with filename "Virtual Studio Code.app" can be search by the query "vsc"

### CODE REVIEW

**Comment by amjith** [comment]
I was under the impression that the app finder plugin was using fuzzy search to match the names. We do use this [library](https://github.com/amjith/fuzzyfind/) in other places of Zazu. 

That fuzzy find library will do what you have implemented.

**Comment by blainesch** [comment]
Agree with @amjith here, the fuzzyfind library would fix this issue in a very nice way. It's used in quite a few plugins right now.

**Comment by blainesch** [comment]
I'd want to make sure we still give weight to the beginning of the word.. for instance the "C" in "google chrome" is more important than the "C" in "Dictionary" Even though it appears first in the ladder.

**Comment by nantaphop** [comment]
Oh just know this library. It look great.

**Comment by blainesch** [comment]
Closing this pull request.

**Pull request closed without merging**
