### PR TITLE
Fixed Linux app finder

### PR DESCRIPTION
**Pull request by JeroenBoersma**
Today I started using zazu, I've found a lot of errors starting software like Nylas or Franz.
After investigating I did some updates.

Will create a new repo for application specific implementation(~/.local/share/applications etc)

- Added ~/bin in lookup for local software
- removed ~/.local/share/applications
- index all executable files, not only other(--x--x--x)
- spawn software directly from main process, starting from subprocess gives a lot of errors(not starting at all)

### CODE REVIEW

**Comment by blainesch** [comment]
Wow, thank you so much for the pull request. I'll try this out and see if it works technically.

@amjith do you mind validating the approach is correct?

**Comment by cecoates** [comment]
@JeroenBoersma 

For funsies I made the same changes as in your pull request. Pretty cool, and I was able to launch most programs (except Invisible Inc. for some reason). 

However, the search felt noticeably slower, and the log is full of "X11/X11/X11/X11". Should that be happening?

I also noticed that by default, a lot of games will have random files marked as executable, like .txt files or map files. So those will come up in the search and create a lot of noise (maybe that's the slowdown?) Is it possible to filter those out? 

[zazu.log (copy).2017-01-11.txt](https://github.com/tinytacoteam/zazu-file-finder/files/698151/zazu.log.copy.2017-01-11.txt)

I deleted the file-finder directory and tried again, and the searches were slightly faster, but Zazu could no longer launch games like Transistor or Stardew Valley.

[zazu.log (another copy).2017-01-11.txt](https://github.com/tinytacoteam/zazu-file-finder/files/698175/zazu.log.another.copy.2017-01-11.txt)

**Comment by JeroenBoersma** [comment]
@cecoates I'll add a recursionchecker for that nasty X11 error(I've removed that symlink on my filesystem) I think stat can say something about that...

Games is not yet in the appPath, will investigate further...

**Comment by JeroenBoersma** [comment]
image

- Added possibility to override directories in `.zazurc.json`
* needs to be applied to filefinder(works for appfinder)

**Comment by JeroenBoersma** [comment]
fixed for filefinder to

**Comment by blainesch** [comment]
This is awesome. I'll review this tonight when I get home.

**Comment by cecoates** [comment]
Very cool!

Gave it a try, and adding directories via the zazurc.json works great.

screenshot from 2017-01-11 19-04-43

**Comment by blainesch** [comment]
Love this [:

**Comment by blainesch** [comment]
I updated the [installation instructions](https://github.com/tinytacoteam/zazu-file-finder#installing) as well.

**Comment by JeroenBoersma** [comment]
Great, the error is because we reject the chain. Otherwise it would be forwarded to the open command.

**Pull request merged**
