### PR TITLE
Fix issue with not being able to find apps on mac.

### PR DESCRIPTION
**Pull request by blainesch**
Mac apps are `.app` and are also directories.

cc: @JeroenBoersma

### CODE REVIEW

**Comment by JeroenBoersma** [comment]
And on Linux they aren't :) 

I've found something to suit both...

**Comment by blainesch** [comment]
@JeroenBoersma what issue are you running into on linux? If on linux a directory can't be an app then I think it'll still be fine.

| isDirectory | isApp  | output  |
|:-----------:| -----:| -----:|
| true  | true  | false |
| true  | false | true |
| false | true  | false |
| false | false | false |

**Comment by JeroenBoersma** [comment]
Under Mac/Linux directories have execute rights to allow browsing so isApp will return true as isDirectory will too.
Only Mac has it own logic for finding apps.

So, we will hit up the first line you describe true && false === false

**Comment by JeroenBoersma** [comment]
https://github.com/tinytacoteam/zazu-file-finder/pull/17 will help you out

**Comment by blainesch** [comment]
Oh, I see what you're saying. I'll check out your pr now.

**Comment by JeroenBoersma** [comment]
Updated https://github.com/tinytacoteam/zazu-file-finder/pull/17

**Pull request merged**
